import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Welcome to movie booker": "Welcome to movie booker",
          "Discover and book cinema tickets with ease": "Discover and book cinema tickets with ease",
          "Log in": "Log in",  
          "Continue To Payment":"Continue To Payment",                  
          "10:30 pm-12:00 pm at Alem cinema": "10:30 pm-12:00 pm at Alem cinema", 
          "9:30 pm-11:00 pm at Ednamol cinema": "9:30 pm-11:00 pm at Ednamol cinema",
          "3:20 am-11:00 am At cinema": "3:20 am-11:00 am At cinema",
          "Join now": "Join now",
          "Continue as a guest": "Continue as a guest",
          "Ethio Cinema": "Ethio Cinema",
          "200 meters away": "200 meters away",
          "Second Cinema": "Second Cinema",
          "meters away 300": "300 meters away",
          "Discover movies and book tickets": "Discover movies and book tickets",
          "enter movie or cinema": "enter movie or cinema",
          "Nearby cinema": "Nearby cinema",
          "More": "More",
         
          "General": "General", 
          "Genres": "Genres",
          "Comedy": "Comedy",
          "Fantasy": "Fantasy",
          "Action": "Action",
          "Horror": "Horror",
          "Documentary": "Documentary",
          "Coming of the robot": "Coming of the robot",
          "Watch": "Watch",
          "Genre": "Genre",
          "Sci_fi": "Sci-fi",
          "Price": "Price",
          "Showtime": "Showtime",
          "Description": "Description",
          "In a not-so-distant future, society teeters on the brink of chaos as a brilliant scientist unleashes a groundbreaking artificial intelligence. A task force is deployed to control the evolving situation. What ensues is a high-stakes game of cat and mouse, where humanity's fate hangs in the balance.": "In a not-so-distant future, society teeters on the brink of chaos as a brilliant scientist unleashes a groundbreaking artificial intelligence. A task force is deployed to control the evolving situation. What ensues is a high-stakes game of cat and mouse, where humanity fate hangs in the balance.",          
          "In to the purple":"In to the purple",
          "Green the grinch":"Green the grinch",
          "little the red boot":"little the red boot",
          "Dino_dog":"Dino dog",
          "Freaky flamingo":"Freaky flamingo",
          "enter movie":"enter movie",
          "Animation":"Animation",
          "Email":"Email",
          "Enter Email":"Enter Email",
          "Enter valid email":"Enter valid email",
          "Password":"Password",
          "Enter password":"Enter password",
          "Forgot_password":"Forgot password",
          "Log In":"Log In",
          "Not a member":"Not a member",
          "Sign Up":"Sign Up",
          "seat":"250/seat",
          "English":"English",
          "Mark":"Mark",
          "Fav Cinema":"Fav Cinema",
          "Movie Interest":"Movie Interest",
          "Payment Method":"Payment Method",
          "Generals":"Generals",
          "Personal info":"Personal info",
          "Notification":"Notification",
          "Security":"Security",
          "Language":"Language",
          "Dark mode":"Dark mode",
          "About":"About",
          "Help center":"Help center",
          "About_us":"About us",
          "Logout":"Logout",
          "Select Language":"Select Language",
          "Review Summary":"Review Summary",
          "Duration":"Duration",
          "128 minutes":"128 minutes",
          "Director":"Director",
          "Nahome":"Nahome",
          "AR":"AR",
          "R17":"R17",
          "Booking Details":"Booking Details",
          "Cinema":"Cinema",
          "AMC Emp 25":"AMC Emp 25",
          "Package":"Package",
          "Standart":"Standart",
          "Auditorium":"Auditorium",
          "Auditorium 3":"Auditorium 3",
          "Date":"Date",
          "Feb 28, 2024":"Feb 28, 2024",
          "Hours":"Hours",
          "F7":"F7",         
          "Action, Sci-fi":"Action, Sci-fi",
          "Price Details":"Price Details",
          "Promo and Vochers":"Promo and Vochers",
          "Enter The promo_code_or_voucher":"Enter The promo code or voucher",
          "Cancel Booking":"Cancel Booking",
          "Continoue To Payment":"Continoue To Payment",
          "First Name":"First Name",
          "Last Name":"Last Name",
          "Remember me":"Remember me",
          "I want to receive email":"I want to receive email",
          "Write a comment":"Write a comment",
          "Send":"Send",
          "Alem Cinema":"Alem Cinema",
          "The trending cinema in Addis":"The trending cinema in Addis",
          "reviews":"2M reviews",
          "Upcoming Show":"Upcoming Show",
          "Today":"Today",
          "10:30 pm-12:00pm at \n Alem cinema":"10:30 PM - 12:PM at\n Alem Cinema",
          "About Alem Cinema":"About Alem Cinema",
          "Welcome to Alem Cinema, a cinematic haven nestled in the heart of Ethiopia, where the magic of storytelling comes to life on the big screen. Alem Cinema stands as a beacon of entertainment, seamlessly blending modernity with Ethiopian cultural richness, offering an immersive cinematic experience like no other.\nAs you step through the doors of Alem Cinema, you are welcomed by an inviting ambiance that reflects the warmth and vibrancy of Ethiopian hospitality.":"Welcome to Alem Cinema, a cinematic haven nestled in the heart of Ethiopia, where the magic of storytelling comes to life on the big screen. Alem Cinema stands as a beacon of entertainment, seamlessly blending modernity with Ethiopian cultural richness, offering an immersive cinematic experience like no other.\nAs you step through the doors of Alem Cinema, you are welcomed by an inviting ambiance that reflects the warmth and vibrancy of Ethiopian hospitality",
          "Show Less":"Show Less",
          "Load More":"Load More",
          "Come Visit Us":"Come Visit Us",
           "XQRP+68P, Airport Road Addis Ababa":"XQRP+68P, Airport Road, Addis Ababa",
           "Check our official Page":"Check our official Page",
           "Send to your phone":"Send to your phone",
           "What people say about us":"What people say about us",
           "Rate Our Cinema":"Rate Our Cinema",
           "Tell others what you think":"Tell others what you think",
           "Rating and reviews are verified and are from people who use the service":"Rating and reviews are verified and are from people who use the service",
           "Write a review":"Write a review",
           "Where do you want to go":"Where do you want to go",
          "Event":"Event",
          "Theatre":"Theatre",
          "Home":"Home",
          "Search":"Search",
          "Explore":"Explore",
          "Person":"Person",
          "Create new password":"Create new password",
          "Create your new password make sure it contains 6 characters, numbers, and special symbols":"Create your new password make sure it contains 6 characters, numbers, and special symbols",
          "New Password":"New Password",
          "Confirm new password":"Confirm new password",
          "Confirm Password":"Confirm Password",
          "Passwords do not match":"Passwords do not match",
          "Continue":"Continue",
          "Reset Password Successful":"Reset Password Successful",
          "OK":"OK",
          "Invalid index":"Invalid index",
          "OTP Code Verification":"OTP Code Verification",
          "We have sent an OTP code to your email mar********ley@yourdomain.com Enter the OTP code below to verify":"We have sent an OTP code to your email mar********ley@yourdomain.com Enter the OTP code below to verify",
          "Didn't receive email?":"Didn't receive email?",
          "You can resend code in":"You can resend code in",
          "Reset Your Password":"Reset Your Password",
          "Please enter your email, and we will send an OTP code in the next step to reset your password.":"Please enter your email, and we will send an OTP code in the next step to reset your password.",
          "Art":"Art",
          "News paper":"News paper",
          "Documentation":"Documentation",
          "Horor":"Horor",
          "10:30 PM - 12:PM at\n Alem Cinema":"10:30 PM - 12:PM at\n Alem Cinema",
         
          "Choose Seats":"Choose Seats",
          "Available":"Available",
          "Token":"Token",
          "Selected":"Selected",
          "Total Price":"Total Price",
          "Seats":"Seats",
          "Personal Info":"Personal Info",
          "User Name":"User Name",
          "Enter User Name":"Enter User Name",
          "Phone Number":"Phone Number",
          "Enter Phone Number":"Enter Phone Number",
          "Gender":"Gender",
          "Male":"Male",
          "Female":"Female",
          "Other":"Other",
          "Save":"Save",
          "Biometric ID":"Biometric ID",
          "Face ID":"Face ID",
          "SMS Authentication":"SMS Authentication",
          "Google Authentication":"Google Authentication",
          "Device Management":"Device Management",
          "Change Password":"Change Password",
          "New Update Available! Update Movier and get a better cinematic experience \nat 09:40 AM.":"New Update Available! Update Movier and get a better cinematic experience \nat 09:40 AM.",
          "Deadpol will be playing this afternoon at vadmad cinema \nat 09:40 AM.":"Deadpol will be playing this afternoon at vadmad cinema \nat 09:40 AM.",
          "Yesterday":"Yesterday",
          "About Movie":"About Movie",
          "Movier v5.7.8":"Movier v5.7.8",
          "Privacy and Policy":"Privacy and Policy",
          "Contact Us":"Contact Us",
          "Partner":"Partner",
          "Accessibility":"Accessibility",
          "Feedback":"Feedback",
          "Rate Us":"Rate Us",
          "Visit Our Website":"Visit Our Website",
          "Follow Us On Social Media":"Follow Us On Social Media",
          "Add Payment":"Add Payment",
          "Card Number":"Card Number",
          "Account Holder Name":"Account Holder Name",
          "Beth Abraham":"Beth Abraham",
          "Expire Date":"Expire Date",
          "Choose Payment Method":"Choose Payment Method",
          "Select Payment Method":"Select Payment Method",
          "Please select a payment method before proceeding.":"Please select a payment method before proceeding.",
          "Add New Payment":"Add New Payment",
          "Confirm Payment":"Confirm Payment", 
          "Are you sure you want to confirm the payment of \$680.00?":"Are you sure you want to confirm the payment of \$680.00?",
          "Cancel":"Cancel",
          "Confirm":"Confirm",
          "Contact us":"Contact us",
          "Call":"Call",
          "Facebook":"Facebook",
          "Linkedin":"Linkedin",
          "Choose Cinema":"Choose Cinema",
          "Your location":"Your location",
          "Addis Ababa":"Addis Ababa",
          "All Cinema":"All Cinema",
          "Favorite":"Favorite",
          "Order Details":"Order Details",
          "Jumbo Popcorn":"Jumbo Popcorn",
          "Indulge in the ultimate movie experience with our movie magic popcorn":"Indulge in the ultimate movie experience with our movie magic popcorn",
          "Note for your food  or drinks":"Note for your food  or drinks",
          "Leave notes here":"Leave notes here",
          "Add to basket":"Add to basket",
          "Food and Order":"Food and Order",
          "Most Popular":"Most Popular",
          "View All":"View All", 
          "Burger and Chips":"Burger and Chips",
          "How to report cinema issues?":"How to report cinema issues?",
          "Can I book my tickets once?":"Can I book my tickets once?",
          "How to cancel or refund tickets?":"How to cancel or refund tickets?",
          "Can I modify booking?":"Can I modify booking?",
          "How do I book tickets?":"How do I book tickets?",
          "What is movier?":"What is movier?",
          "Search...":"Search...",
          "Payment":"Payment",
          "Account":"Account",
          "Help Center":"Help Center",
          "Romance":"Romance",
          "Mystery":"Mystery",
          "Science Fiction":"Science Fiction",
          "Thriller":"Thriller",
          "Crime":"Crime",
          "Western":"Western",
          "Pick up time":"Pick up time",          
          "Sports":"Sports",
          "Adventure":"Adventure",
          "Musical":"Musical",
          "Historical":"Historical",
          "Travel":"Travel",
          "Biographical":"Biographical",
          "Psychological":"Psychological",
          "Family":"Family",
          "Supernatural":"Supernatural",
          "Zombie":"Zombie",
          "Drama":"Drama",
          "Martial Arts":"Martial Arts",
          "War":"War",         
          "Yes Logout": "Yes Logout",
          "Order Summary":"Order Summary",
          "You need to choose your time'":"You need to choose your time'",
          "Jumbo popcorn(x1)":"Jumbo popcorn(x1)",
          "Service Fee":"Service Fee",
          "Actual Pay":"Actual Pay",
          "Enter The promo code or voucher":"Enter The promo code or voucher",
          "Purchase and pick up of food or drinks can only be done on the same day.\n\n":"Purchase and pick up of food or drinks can only be done on the same day.\n\n",
          "If you order food or drinks to watch a movie, we recommend picking it up 10 minutes before the movie starts.":"If you order food or drinks to watch a movie, we recommend picking it up 10 minutes before the movie starts.",
          "The privacy and policies related to online cinema ticket booking can vary among different platforms and service providers. However, there are common elements that are typically addressed in such policies. Here are some general aspects you might find in the privacy and policies of online cinema ticket booking platforms:":"The privacy and policies related to online cinema ticket booking can vary among different platforms and service providers. However, there are common elements that are typically addressed in such policies. Here are some general aspects you might find in the privacy and policies of online cinema ticket booking platforms:",
          "Personal Information Collection":"Personal Information Collection",
          "The policies usually outline what types of personal information will be collected during the booking process. This may include details such as your name, contact information, payment details, and sometimes demographic information.":"The policies usually outline what types of personal information will be collected during the booking process. This may include details such as your name, contact information, payment details, and sometimes demographic information.",
          "Data Usage":"Data Usage",
          "Platforms typically specify how they will use the collected information. This can include processing your ticket orders, sending you relevant notifications, and possibly using the data for marketing purposes.":"Platforms typically specify how they will use the collected information. This can include processing your ticket orders, sending you relevant notifications, and possibly using the data for marketing purposes.",
          "Security Measures":"Security Measures",
          "The policies often describe the security measures in place to protect your personal information. This may include encryption methods for sensitive data and secure payment gateways.":"The policies often describe the security measures in place to protect your personal information. This may include encryption methods for sensitive data and secure payment gateways.",
          "Cookies and Tracking":"Cookies and Tracking",
          "Platforms may use cookies or other tracking technologies to enhance user experience and gather information about website usage. The policies usually explain the purpose of such technologies and how you can manage your preferences.":"Platforms may use cookies or other tracking technologies to enhance user experience and gather information about website usage. The policies usually explain the purpose of such technologies and how you can manage your preferences.",
          "Third-Party Sharing":"Third-Party Sharing",
          "The policies often state whether the platform shares your information with third parties. This can include sharing data with cinema partners or other service providers.":"The policies often state whether the platform shares your information with third parties. This can include sharing data with cinema partners or other service providers.",
          "Retention Period":"Retention Period",
          "Platforms usually specify how long they will retain your personal information. This can vary depending on legal requirements and business needs.":"Platforms usually specify how long they will retain your personal information. This can vary depending on legal requirements and business needs.",
          "User Rights":"User Rights",
          "Your rights regarding your personal information are often outlined in the policies. This may include the right to access, correct, or delete your data.":"Your rights regarding your personal information are often outlined in the policies. This may include the right to access, correct, or delete your data.",
          "Legal Compliance":"Legal Compliance",
          "Platforms typically outline their commitment to complying with relevant data protection laws and regulations.":"Platforms typically outline their commitment to complying with relevant data protection laws and regulations.",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platform customer support for clarification":"It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platform customer support for clarification",
          "Old Password":"Old Password",
          "New":"New",
          "Forgot password?":"Forgot password?",
          "Not a member?":"Not a member?",
          "Watched":"Watched",
          "Booking Confirmation":"Booking Confirmation",
          "Cinema Rating":"Cinema Rating",
          "Order Update":"Order Update",
          "Seat Availability Alert":"Seat Availability Alert",
          "Ticket Reminder":"Ticket Reminder",
          "Connected":"Connected",
          "Confirm Payment-\$680.00":"Confirm Payment-\$680.00",
          "Release date":"Release date",
          "Age":"Age",
          "Rating":"Rating",
          "Location":"Location",
          "Amharic":"Amharic",
          "Afaan Oromoo":"Afaan Oromoo",
          "Tigrigna":"Tigrigna",
         "Trending filters":"Trending filters",
          "Filter by":"Filter by",
          "Search A movie":"Search A movie",
          "Time:":"Time:",
          
          "I want to recieve email": "I want to recieve email",
          
          "Date:":"Date:",          
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platforms customer support for clarification":"It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platforms customer support for clarification", 
          "Are you sure you want to logout?": "Are you sure you want to logout?",
          "Nearby Theatre":"Nearby Theatre",          
          "enter location:":"enter location:"
         
        
           },
        'am': {
          "Welcome to\nmovie booker": "ወደ ፊልም አዘጋጅ \nእንኳን በደህና መጡ",
          "Discover and book cinema tickets with ease": "በቀላሉ የሲኒማ ትኬቶችን ያግኙ እና ይያዙ",
          "Log in": "ግባ",
          "10:30 pm-12:00 pm at Alem cinema": "ከቀኑ 10፡30-12፡00 በአለም ሲኒማ",     
         "Continue To Payment":"መክፈሉን ይቀጥሉ", 
          
          "9:30 pm-11:00 pm at Ednamol cinema": "ከቀኑ 9፡30 - 11፡00 በኤድናሞል ሲኒማ",
          "3:20 am-11:00 am At cinema": "ከጠዋቱ 3፡20-11፡00 በሲኒማ",
          
          "About Movie": "ስለ ፊልም",
          "Join now": "አሁን ይቀላቀሉ",
          "Continue as a guest": "እንደ እንግዳ ቀጥል",
          "Ethio Cinema": "ኢትዮ ሲኒማ",
          "200 meters away": "200 ሜትር ርቀት",
          "Second Cinema": "ሁለተኛ ሲኒማ",
          "300 meters away": "300 ሜትር ርቀት",
          "Discover movies and ""book tickets": "ፊልሞችን ያግኙ እና ቲኬቶችን ይያዙ",
          "enter movie or cinema": "ፊልም ወይም ሲኒማ ያስገቡ",
          "Nearby cinema": "የአቅራቢያ ሲኒማ",
          "More": "ተጨማሪ",
          "Genres": "ዘውጎች",
          "Comedy": "አስቂኝ",
          "Fantasy": "ምናባዊ",
          "Action": "ድርጊት",
          "Horror": "አስፈሪ",
          "Documentary": "ዘጋቢ ፊልም",
          "Coming of the Robot": "የሮቦት መምጣት",
          "Coming of the robot": "የሮቦት መምጣት",
          "Watch": "ይመልከቱ",
          "Genre": "ዘውግ",
          "Seat(s)":"መቀመጫ(ዎች)",
          "Sci-fi": "ስኪፍ",
          "Price": "ዋጋ",
          "Showtime": "የማሳያ ጊዜ",
          "Description": "መግለጫ",
          "In a not-so-distant future, society teeters on the brink of chaos as a brilliant scientist unleashes a groundbreaking artificial intelligence. A task force is deployed to control the evolving situation. What ensues is a high-stakes game of cat and mouse, where humanity's fate hangs in the balance.": "ብዙም በማይርቅ ጊዜ ውስጥ፣ አንድ ድንቅ ሳይንቲስት እጅግ አስደናቂ የሆነ አርቴፊሻል ኢንተለጀንስ ሲያወጣ ህብረተሰቡ ትርምስ አፋፍ ላይ ወድቋል። እየተሻሻለ የመጣውን ሁኔታ ለመቆጣጠር ግብረ ሃይል ተዘርግቷል። ይህን ተከትሎ የሚመጣው የሰው ልጅ እጣ ፈንታ በሚዛን ላይ የሚንጠለጠልበት የድመት እና የአይጥ ከፍተኛ ጨዋታ ነው።",
          "In to the purple":"ወደ ሐምራዊው ውስጥ",
          "Green the grinch":"አረንጓዴ ግሪንች",
          "little the red boot":"ትንሽ ቀይ ቦት",
          "Dino dog":"ዲኖ ውሻ",
          "Freaky flamingo":"አስፈሪ ፍላሚንጎ",
          "enter movie":"ፊልም አስገባ",
          "Animation":"አኒሜሽን",
          "Email":"ኢሜይል",
          "Enter Email":"ኢሜል አስገባ",
          "Enter valid email":"የሚሰራ ኢሜይል ያስገቡ",
          "Password":"የይለፍ ቃል",
          "Enter password":"የይለፍ ቃል ያስገቡ",
          "Forgot password?":"መክፈቻ ቁልፉን ረሳኽው",
          "Log In":"ግባ",
          "Not a member?":"አባል አይደለም?", 
          "Sign Up":"ተመዝገቢ",
          "250/seat":"250/መቀመጫ",
          "English":"እንግሊዝኛ",
          "Mark":"ማርክ",
          "Fav Cinema":"ፈቭ ሲኒማ",
          "Movie Interest":"የፊልም ፍላጎት",
          "Payment Method":"የመክፈያ ዘዴ",
          "Generals":"አጠቃላይ",
          "Personal info":"የግል መረጃ",
          "Notification":"ማስታወቂያ",
          "Security":"ደህንነት",
          "Language":"ቋንቋ",
          "Dark mode":"ጨለማ",
          "About":"ስለ",
          "Help center":"የእገዛ ማዕከል",
          "About us":"ስለ እኛ",
          "Logout":"ውጣ",
          "Select Language":"ቋንቋ ይምረጡ",
          "Review Summary":"የግምገማ ማጠቃለያ",
          "Duration":"ቆይታ",
          "128 minutes":"128 ደቂቃዎች",
          "Director":"ዳይሬክተር",
          "Nahome":"ናሆም",
          "AR":"AR",
          "R17":"R17",
          "Booking Details":"የቦታ ማስያዝ ዝርዝሮች",
          "Cinema":"ሲኒማ",
          "AMC Emp 25":"AMC Emp 25",
          "Package":"ጥቅል",
          "Standart":"መደበኛ",
          "Auditorium":"የመሰብሰቢያ አዳራሽ",
          "Auditorium 3":"የመሰብሰቢያ አዳራሽ 3",
          "Date":"ቀን",
          "Feb 2024":"የካትት 28፣ 2024",
          "Hours":"ሰዓታት",
          "F7":"ፈ7",
           "Price Details":"የዋጋ ዝርዝሮች",
          "Promo and Vochers":"ፕሮሞ እና ቮቸሮች",
          "Enter The promo code or voucher":"የማስተዋወቂያ ኮዱን ወይም ቫውቸር ያስገቡ",
           "Cancel Booking":"ቦታ ማስያዝ ሰርዝ",
           "Continoue To Payment":"ወደ ክፍያ ቀጥል",
            "First Name":"የመጀመሪያ ስም",
           "Last Name":"የአያት ስም",
           "Remember me":"አስታወስኝ",
           "I want to receive email":"ኢሜል መቀበል እፈልጋለሁ",
            "Write a comment":"አስተያየት ጻፍ",
           "Send":"ላክ",
           "Alem Cinema":"አለም ሲኒማ",
           "The trending cinema in Addis":"በመታየት ላይ ያለው ሲኒማ በአዲስ",
           "reviews":"2M ግምገማዎች",
           "Upcoming Show":"መጪ ትዕይንት",
           "Today":"ዛሬ",
           "10:30 pm-12:00pm at \n Alem cinema":"10:30 PM - 12:PM በአለም ሲኒማ",
           "About Alem Cinema":"About Alem Cinema",
           "Welcome to Alem Cinema, a cinematic haven nestled in the heart of Ethiopia, where the magic of storytelling comes to life on the big screen. Alem Cinema stands as a beacon of entertainment, seamlessly blending modernity with Ethiopian cultural richness, offering an immersive cinematic experience like no other.\nAs you step through the doors of Alem Cinema, you are welcomed by an inviting ambiance that reflects the warmth and vibrancy of Ethiopian hospitality.":"እንኳን ወደ አለም ሲኒማ እንኳን ደህና መጣህ ፣ በኢትዮጵያ እምብርት ላይ ወደሚገኝ የሲኒማ ቤት ፣ የታሪክ አስማት በትልቁ ስክሪን ላይ ይታያል። አለም ሲኒማ እንደ መዝናኛ ብርሃን ሆኖ ቆሞ ዘመናዊነትን ከኢትዮጵያዊ የባህል ብልጽግና ጋር በማዋሃድ እንደሌላው እጅግ መሳጭ የሲኒማ ገጠመኞችን ይሰጣል። እና የኢትዮጵያውያን መስተንግዶ ንቁነት",
           "Show Less":"ያነሰ አሳይ",
           "Load More":"ተጨማሪ ይጫኑ",
           "Come Visit_Us":"ይምጡ ይጎብኙን",
           "XQRP+68P, Airport Road Addis Ababa":"XQRP+68P, አየር ማረፊያ መንገድ፣ አዲስ አበባ",
           "Check our official Page":"የእኛን ኦፊሴላዊ ገጽ ይመልከቱ",
           "Send to your phone":"ወደ ስልክህ ላክ",
           "What people say about us":"ሰዎች ስለ እኛ ምን ይላሉ",
           "Rate Our Cinema":"የእኛን ሲኒማ ደረጃ ይስጡ",
           "Tell others what you think":"ምን እንደሚያስቡ ለሌሎች ይንገሩ",
           "Rating and reviews are verified and are from people who use the service":"ደረጃዎች እና ግምገማዎች የተረጋገጡ እና አገልግሎቱን ከሚጠቀሙ ሰዎች የተገኙ ናቸው",
           "Write a review":"አንድ ግምገማ ጻፍ",
            "Where do you want to go":"ወዴት መሄድ ትፈልጋለህ?",
            "Event":"ክስተት",
            "Theatre":"ቲያትር",
            "Home":"ቤት",
            "Amharic":"አማርኛ",            
            "Search":"ፈልግ",
            "Explore":"ያስሱ",
            "Action, Sci-fi":"ድርጊት, ስኪፍ",
            "Person":"ሰው",
          "Create new password":"አዲስ የይለፍ ቃል ይፍጠሩ",
          "Create your new password make sure it contains 6 characters, numbers, and special symbols":"አዲሱን የይለፍ ቃልዎን ይፍጠሩ 6 ቁምፊዎች፣ ቁጥሮች እና ልዩ ምልክቶች መያዙን ያረጋግጡ",
          "New Password":"አዲስ የይለፍ ቃል",
          "Confirm new password":"አዲሱን የይለፍ ቃል አረጋግጥ",
          "Confirm Password":"የይለፍ ቃል አረጋግጥ",
          "Passwords do not match":"የይለፍ ቃሎች ተመሳሳይ አይደሉም",
          "Continue":"ቀጥል",
          "Reset Password Successful":"የይለፍ ቃል ዳግም ማስጀመር ተሳክቷል",
          "OK":"እሺ",
          "Invalid index":"ልክ ያልሆነ መረጃ ጠቋሚ",
          "OTP Code Verification":"የኦቲፒ ኮድ ማረጋገጫ",
          "We have sent an OTP code to your email mar********ley@yourdomain.com Enter the OTP code below to verify":"የ OTP ኮድ ወደ ኢሜልዎ ልከናል mar********ley@yourdomain.com ለማረጋገጥ የኦቲፒ ኮድ ከዚህ በታች ያስገቡ",
          "Didn't receive email?":"ኢሜይል አልደረሰህም?",
          "You can resend code in":"ኮድ ወደ ውስጥ እንደገና መላክ ይችላሉ",
          "Reset Your Password":"የይለፍ ቃልዎን ዳግም ያስጀምሩ",
          "Please enter your email, and we will send an OTP code in the next step to reset your password.":"እባክዎ ኢሜልዎን ያስገቡ እና የይለፍ ቃልዎን እንደገና ለማስጀመር በሚቀጥለው ደረጃ የኦቲፒ ኮድ እንልካለን",
          "Art":"ስነ ጥበብ",
          "News paper":"የዜና ወረቀት",
          "Documentation":"ሰነድ",
          "Horor":"ሆረር",
         "Where do you want to go?":"ወዴት መሄድ ትፈልጋለህ?",
          "10:30 PM - 12:PM at\n Alem Cinema":"10:30 PM - 12:PM በአለም ሲኒማ",
          "Choose Seats":"መቀመጫዎችን ይምረጡ",
          "Available":"ይገኛል",
          "Token":"ማስመሰያ",
          "Selected":"ተመርጧል",
          "Total Price":"ጠቅላላ ዋጋ",
          "Seats":"መቀመጫዎች",
          "Personal Info":"የግል መረጃ",
          "User Name":"የተጠቃሚ ስም",
          "Enter User Name":"የተጠቃሚ ስም ያስገቡ",
          "Phone Number":"ስልክ ቁጥር",
          "Enter Phone Number":"ስልክ ቁጥር ያስገቡ",
          "Gender":"ጾታ",
          "Male":"ወንድ",
          "Female":"ሴት",
          "Other":"ሌላ",
          "Save":"አስቀምጥ",
          "Biometric ID":"የባዮሜትሪክ መታወቂያ",
          "Face ID":"የፊት መታወቂያ",
          "SMS Authentication":"የኤስኤምኤስ ማረጋገጫ",
          "Google Authentication":"ጉግል ማረጋገጫ",
          "Device Management":"የመሣሪያ አስተዳደር",
          "Change Password":"የሚስጥር ቁልፍ ይቀይሩ",
          "New Update Available! Update Movier and get a better cinematic experience \nat 09:40 AM.":"አዲስ ማሻሻያ አለ! ፊልምን ያዘምኑ እና የተሻለ የሲኒማ ልምድ ያግኙ \nat 09:40 AM",
          "Deadpol will be playing this afternoon at vadmad cinema \nat 09:40 AM.":"ዴድፖል ዛሬ ከሰአት በኋላ በቫድማድ ሲኒማ ይጫወታል \nat 09:40 AM",
          "Yesterday":"ትናንት",
          "Movier v5.7.8":"ፊልም ሰሪ v5.7.8",
          "Privacy and Policy":"ግላዊነት እና ፖሊሲ",
          "Contact Us":"አግኙን",
          "Partner":"አጋር",
          "Accessibility":"ተደራሽነት",
          "Feedback":"ግብረ መልስ",
          "Rate Us":"ደረጃ ይስጡን",
          "Visit Our Website":"የእኛን ድረ-ገጽ ይጎብኙ",
          "Follow Us On Social Media":"በማህበራዊ ሚዲያ ላይ ይከተሉን",
          "Add Payment":"ክፍያ ጨምር",
          "Card Number":"የካርታ ቁጥር",
          "Account Holder Name":"መለያ ያዥ ስም",
          "Beth Abraham":"ቤተ አብርሃም",
          "Expire Date":"ጊዜው የሚያበቃበት ቀን",        
           "Choose Payment Method":"የመክፈያ ዘዴን ይምረጡ",
          "Select Payment Method":"የመክፈያ ዘዴን ይምረጡ",
          "Please select a payment method before proceeding.":"እባክዎ ከመቀጠልዎ በፊት የመክፈያ ዘዴ ይምረጡ",
          "Add New Payment":"አዲስ ክፍያ ጨምር",
          "Confirm Payment":"ክፍያ ያረጋግጡ", 
          "Are you sure you want to confirm the payment of \$680.00?":"እርግጠኛ ነህ የ 680.00 ክፍያ ማረጋገጥ ትፈልጋለህ?",
          "Cancel":"ሰርዝ",
          "Confirm":"አረጋግጥ",
          "Contact us":"አግኙን",
          "Call":"ይደውሉ",
          "Facebook":"ፌስቡክ",
          "Linkedin":"ሊንክዲን",
          "Choose Cinema":"ሲኒማ ይምረጡ",
          "Your location":"አካባቢህ",
          "Addis Ababa":"አዲስ አበባ",
          "All Cinema":"ሁሉም ሲኒማ",
          "Favorite":"የሚወደድ",
          "Order Details":"የትዕዛዝ ዝርዝሮች",
          "Jumbo Popcorn":"ጃምቦ ፖፕኮርን",
          "Indulge in the ultimate movie experience with our movie magic popcorn":"በእኛ የፊልም አስማት ፋንዲሻ ወደ የመጨረሻው የፊልም ልምድ ይግቡ",
          "Note for your food  or drinks":"ለምግብዎ ወይም ለመጠጥዎ ማስታወሻ",
          "Leave notes here":"ማስታወሻዎችን እዚህ ይተው",
          "Add to basket":"ቅርጫቱ ውስጥ ይጨምሩ",
          "Food and Order":"ምግብ እና ትዕዛዝ",
          "Most Popular":"በጣም ታዋቂ",
          "View All":"ሁሉንም ይመልከቱ", 
          "Burger and Chips":"በርገር እና ቺፕስ",
          "How to report cinema issues?":"የሲኒማ ጉዳዮችን እንዴት \nሪፖርት ማድረግ እንደሚቻል?",
          "Can I book my tickets once?":"ቲኬቶቼን አንድ ጊዜ \nመያዝ እችላለሁ?",
          "How to cancel or refund tickets?":"ትኬቶችን እንዴት መሰረዝ\n ወይም መመለስ ይቻላል?",
          "Can I modify booking?":"ቦታ ማስያዝን \nማስተካከል እችላለሁ?",
          "How do I book tickets?":"ቲኬቶችን እንዴት\n ማስያዝ እችላለሁ?",
          "What is movier?":"ፊልም ምንድን ነው?",
          "Search...":"ፈልግ...",
          "Payment":"ክፍያ",
          "Old Password":"የድሮ የይለፍ ቃል",          
          "Account":"መለያ",
          "Help Center":"የእገዛ ማዕከል",
          "Romance":"የፍቅር ጓደኝነት",
          "Mystery":"ምስጢር",
          "Science Fiction":"የሳይንስ ልብወለድ",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platforms customer support for clarification":"መረጃዎ እንዴት እንደሚስተናገድ ለመረዳት እና አገልግሎቱን ስለመጠቀም በመረጃ ላይ የተመሰረተ ውሳኔ ለማድረግ እየተጠቀሙበት ያለውን ልዩ የመስመር ላይ ሲኒማ ቲኬት ማስያዣ መድረክን የግላዊነት ፖሊሲ በጥንቃቄ ማንበብ አስፈላጊ ነው። የተወሰኑ ስጋቶች ወይም ጥያቄዎች ካሉዎት፣ ለማብራርያ የደንበኛ ድጋፍ ሰጪዎችንም ማግኘት ይችላሉ።",          
          "Thriller":"ትሪለር",
          "Crime":"ወንጀል",         
          "Western":"ምዕራባዊ",
          "Sports":"ስፖርት",
          "Adventure":"ጀብዱ",
          "Musical":"ሙዚቃዊ",
          "Historical":"ታሪካዊ",
          "Travel":"ጉዞ",
          "Biographical":"ባዮግራፊያዊ",
          "Psychological":"ሳይኮሎጂካል",
          "Family":"ቤተሰብ",
          "Supernatural":"ከተፈጥሮ በላይ የሆነ",
          "Zombie":"ዞምቢ",
          "Drama":"ድራማ",
          "Martial Arts":"ማርሻል አርት",
          "War":"ጦርነት",
          "Order Summary":"የትዕዛዝ ማጠቃለያ",
          "Pick up time":"የመውሰጃ ጊዜ",
          "You need to choose your time":"ጊዜዎን መምረጥ ያስፈልግዎታል",
          "Jumbo popcorn(x1)":"ጃምቦ ፋንዲሻ (x1)",
          "Service Fee":"የአገልግሎት ክፍያ",
          "Actual Pay":"ትክክለኛ ክፍያ",        
          "Purchase and pick up of food or drinks can only be done on the same day.\n\n":"ምግብ ወይም መጠጥ መግዛት እና ማንሳት ሊደረግ የሚችለው በተመሳሳይ ቀን ብቻ ነው",
          "If you order food or drinks to watch a movie, we recommend picking it up 10 minutes before the movie starts.":"ፊልም ለማየት ምግብ ወይም መጠጥ ካዘዙ ፊልሙ ከመጀመሩ 10 ደቂቃ በፊት እንዲወስዱት እንመክራለን",
          "The privacy and policies related to online cinema ticket booking can vary among different platforms and service providers. However, there are common elements that are typically addressed in such policies. Here are some general aspects you might find in the privacy and policies of online cinema ticket booking platforms:":"ከመስመር ላይ ሲኒማ ቲኬት ቦታ ማስያዝ ጋር የተያያዙ ግላዊነት እና ፖሊሲዎች በተለያዩ መድረኮች እና አገልግሎት አቅራቢዎች ሊለያዩ ይችላሉ። ነገር ግን፣ በእንደዚህ አይነት ፖሊሲዎች ውስጥ በተለምዶ የሚነሱ የተለመዱ ነገሮች አሉ። በመስመር ላይ ሲኒማ ቲኬት ማስያዣ መድረኮች ግላዊነት እና ፖሊሲዎች ውስጥ ሊያገኟቸው የሚችሏቸው አንዳንድ አጠቃላይ ገጽታዎች እዚህ አሉ",
          "Personal Information Collection":"የግል መረጃ ስብስብ",
          "The policies usually outline what types of personal information will be collected during the booking process. This may include details such as your name, contact information, payment details, and sometimes demographic information.":"ፖሊሲዎቹ በቦታ ማስያዝ ሂደት ውስጥ ምን አይነት የግል መረጃ እንደሚሰበሰቡ ይገልፃሉ። ይህ እንደ ስምዎ፣ የእውቂያ መረጃዎ፣ የክፍያ ዝርዝሮችዎ እና አንዳንድ ጊዜ የስነሕዝብ መረጃ ያሉ ዝርዝሮችን ሊያካትት ይችላል",
          "Data Usage":"የውሂብ አጠቃቀም",
          "Platforms typically specify how they will use the collected information. This can include processing your ticket orders, sending you relevant notifications, and possibly using the data for marketing purposes.":"መድረኮች በተለምዶ የተሰበሰበውን መረጃ እንዴት እንደሚጠቀሙ ይገልጻሉ። ይህ የቲኬት ትዕዛዞችን ማካሄድን፣ ተዛማጅ ማስታወቂያዎችን መላክ እና ምናልባትም ውሂቡን ለገበያ ዓላማ መጠቀምን ሊያካትት ይችላል",
          "Security Measures":"የደህንነት እርምጃዎች",
          "The policies often describe the security measures in place to protect your personal information. This may include encryption methods for sensitive data and secure payment gateways.":"ፖሊሲዎቹ የእርስዎን የግል መረጃ ለመጠበቅ ብዙ ጊዜ የደህንነት እርምጃዎችን ይገልፃሉ። ይህ ሚስጥራዊ ለሆኑ መረጃዎች እና ደህንነቱ የተጠበቀ የክፍያ መግቢያ መንገዶችን የማመስጠር ዘዴዎችን ሊያካትት ይችላል",
          "Cookies and Tracking":"ኩኪዎች እና ክትትል",
          "Platforms may use cookies or other tracking technologies to enhance user experience and gather information about website usage. The policies usually explain the purpose of such technologies and how you can manage your preferences.":"የመሣሪያ ስርዓቶች የተጠቃሚን ልምድ ለማሻሻል እና ስለድር ጣቢያ አጠቃቀም መረጃ ለመሰብሰብ ኩኪዎችን ወይም ሌሎች የመከታተያ ቴክኖሎጂዎችን ሊጠቀሙ ይችላሉ። ፖሊሲዎቹ ብዙውን ጊዜ የእነዚህን ቴክኖሎጂዎች ዓላማ እና ምርጫዎችዎን እንዴት ማስተዳደር እንደሚችሉ ያብራራሉ",
          "Third-Party Sharing":"የሶስተኛ ወገን መጋራት",
          "The policies often state whether the platform shares your information with third parties. This can include sharing data with cinema partners or other service providers.":"ፖሊሲዎቹ ብዙ ጊዜ መድረኩ የእርስዎን መረጃ ለሶስተኛ ወገኖች ማጋራቱን ወይም አለመሆኑን ይገልፃሉ። ይህ መረጃን ከሲኒማ አጋሮች ወይም ከሌሎች አገልግሎት አቅራቢዎች ጋር መጋራትን ሊያካትት ይችላል",
          "Retention Period":"የማቆያ ጊዜ",
          "Platforms usually specify how long they will retain your personal information. This can vary depending on legal requirements and business needs.":"መድረኮች አብዛኛውን ጊዜ የእርስዎን ግላዊ መረጃ ለምን ያህል ጊዜ እንደሚይዙ ይገልጻሉ። ይህ እንደ ህጋዊ መስፈርቶች እና የንግድ ፍላጎቶች ሊለያይ ይችላል",
          "User Rights":"የተጠቃሚ መብቶች",
          "Your rights regarding your personal information are often outlined in the policies. This may include the right to access, correct, or delete your data.":"የእርስዎን የግል መረጃ በተመለከተ ያለዎት መብቶች ብዙውን ጊዜ በመመሪያዎቹ ውስጥ ተዘርዝረዋል። ይህ የእርስዎን ውሂብ የመድረስ፣ የማረም ወይም የመሰረዝ መብትን ሊያካትት ይችላል",
          "Legal Compliance":"የሕግ ተገዢነት",
          "Platforms typically outline their commitment to complying with relevant data protection laws and regulations.":"መድረኮች በተለምዶ የውሂብ ጥበቃ ህጎችን እና ደንቦችን ለማክበር ያላቸውን ቁርጠኝነት ይገልፃሉ",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platform customer support for clarification":"መረጃዎ እንዴት እንደሚስተናገድ ለመረዳት እና አገልግሎቱን ስለመጠቀም በመረጃ ላይ የተመሰረተ ውሳኔ ለማድረግ እየተጠቀሙበት ያለውን ልዩ የመስመር ላይ ሲኒማ ቲኬት ማስያዣ መድረክን የግላዊነት ፖሊሲ በጥንቃቄ ማንበብ አስፈላጊ ነው። የተወሰኑ ስጋቶች ወይም ጥያቄዎች ካሉዎት፣ እንዲሁም ለማብራራት ወደ መድረክ የደንበኛ ድጋፍ ማግኘት ይችላሉ",
          "New":"አዲስ",
          "Watched":"ታይቷል",
           "Booking Confirmation":"ቦታ ማስያዝ ማረጋገጫ",
          "Cinema Rating":"የሲኒማ ደረጃ አሰጣጥ",
          "Order Update":"አዘምን አዘምን",
          "Seat Availability Alert":"የመቀመጫ ተገኝነት ማንቂያ",
          "Ticket Reminder":"የቲኬት አስታዋሽ",
          "Connected":"ተገናኝቷል",
          "Confirm Payment-\$680.00":"ክፍያ ያረጋግጡ-\$680.00",
          "Release date":"ይፋዊ ቀኑ",
          "Age":"ዕድሜ",          
          "Rating":"ደረጃ መስጠት",
          "Location":"አካባቢ",
        
          "I want to recieve email": "ኢመይል ክቕበል ደልየ ኣለኹ",
          
          "Enter Password": "ኣእትዉ መሕለፊ ቓል",
          "Afaan Oromoo":"Afaan Oromoo",
          "Tigrigna":"ትግርኛ",
         "Trending filters":"በመታየት ላይ ያሉ ማጣሪያዎች",
          "Filter by":"አጣራ",
          "Search A movie":"ፊልም ይፈልጉ",
          "Time:":"ጊዜ፡-",
          "Date:":"ቀን፡-",
          "Yes Logout": "አዎ ውጣ",
          "General": "አጠቃላይ", 
          "Nearby Theatre":"በአቅራቢያ ቲያትር",
           "Are you sure you want to logout?": "እርግጠኛ ነህ ዘግተህ መውጣት ትፈልጋለህ?",
          "enter location:":"ቦታ አስገባ"
        },
        "om": {
          "Welcome to\nmovie booker": "Baga nagaan gara\n fiilmii dhuftan",
          "Discover and book cinema tickets with ease": "Tikkeetii siniimaa salphaatti argachuu fi buufachuu",
          "Log in": "Seeni", 
          "General": "Waliigala",
          "You need to choose your time":"Yeroo keessan filachuu qabdu",
          "Coming of the Robot":"Dhufaatii Roobootii",
          "Yes Logout": "Eeyyee Ba'i",
          "Continue To Payment":"Kaffaltiitti Fufaa", 
          "Are you sure you want to logout?": "Ba'uu ni barbaadduu",          
          "Join now": "Maammila ta'aa",
          "Continue as a guest": "Akka keessummaatti seenaa",
          "Ethio Cinema": "Ethio Siniimaa",
           "Where do you want to go?":"Eessa deemuu barbaaddu?",
          "200 meters away": "200m",
          "Second Cinema": "Siniimaa 2ffaa",
          "meters away 300": "300m",
          "Discover movies and book tickets": "Tikkeettii murachuun fiilmii argadhaa",
          "enter movie or cinema": "Fiilmii ykn siniimaa galchaa",
          "Nearby cinema": "Siniimaatti dhiyoo",
          "More": "Dabalata",
          "Genres": "Gosa_artii",
          "Comedy": "Komedii",
          "Fantasy": "Fantasy",
          "Action": "Gocha",
          "Horror": "Naasisaa",
          "Documentary": "Dookumantarii",
          "Coming of the robot": "Dhufaatii roobotii",
          "Watch": "Ilaalaa",
          "Genre": "Gosa_artii",
          "Sci_fi": "Saayinsii-faayi",
          "Price": "Gatii",
          "Showtime": "Yeroo_agarsiisaa",
          "Description": "Ibsa",
          "In a not-so-distant future, society teeters on the brink of chaos as a brilliant scientist unleashes a groundbreaking artificial intelligence. A task force is deployed to control the evolving situation. What ensues is a high-stakes game of cat and mouse, where humanity's fate hangs in the balance.": "Fuuldura fagoo hin taane keessatti, hawaasni qarqara jeequmsaa irratti kan raafamu yoo ta'u, saayintistiin qaroo ta'e tokko sammuu namtolchee lafa qabsiisu tokko gadi lakkisee jira. Haala jijjiiramaa jiru to’achuuf gareen hojii bobbaafama. Wanti itti aanu tapha saree fi hantuutaa gatii guddaa qabu yoo ta'u, hireen dhala namaa madaallii irratti fannifamee jira.",          
          "In to the purple":"Gara dhiingee",
          "Green the grinch":"Bo'aarsaa",
          "little the red boot":"Rooborii diimtuu xiqqoo",
          "Dino dog":"Saree diinoo",
          "Freaky flamingo":"Filaamingoo haaraa",
          "enter movie":"Fiilmii galchaa",
          "Animation":"Fakkina",
          "Email":"Imeelii",
          "Movier v5.7.8": "Fiilmii v5.7.8",
          "Enter Email":"Imeelii galchaa",
          "Enter valid email":"Imeeliin galchitan dogoggora",
          "Password":"Iggita",
          "Enter password":"Iggita galchaa",
          "Forgot password":"Iggita dagadheera",
          "Log In":"Seeni",
          "Not a member":"Maammila mit",
          "Sign Up":"Galmaa'aa",
          "seat":"250/Teessuma",
          "English":"English",
          "Mark":"Marki",
          "Fav Cinema":"Siniimaa_jaalatamaa",
          "Movie Interest":"Fedhii fiilmii",
          "Payment Method":"Karaalee kaffaltii",
          "Generals":"Waliigala",
          "Personal info":"Odeeffannoo dhuunfaa",
          "Notification":"Beeksia",
          "Security":"Icciitii",
          "Language":"Afaanota",
          "Dark mode":"Dukkanaa'aa",
          "About":"Waa'ee",
          "Help center":"Giddugala gargaarsaa",
          "About_us":"Waa'ee Keenya",
          "Logout":"Ba'i",
          "Select Language":"Afaanota Filadhaa",
           "Review Summary":"Cuunfaa irra deebiin",
          "Duration":"Turtii",
          "128 minutes":"daqiiqaa 128",
          "Director":"Qindeessaa",
          "Nahome":"Nahome",
          "AR":"AR",
          "R17":"R17",
          "Booking Details":"Akkaataa bakka qabannaa",
          "Cinema":"Siniimaa",
          "AMC Emp 25":"AMC Emp 25",
          "Package":"Kuufama",
          "Standart":"Durtii",
          "Auditorium":"Oditeeriyeemii",
          "Auditorium 3":"Oditeeriyeemii 3",
          "Date":"Guyyaa",
          
          "Feb 28, 2024":"Fulbaana 28, 2024",
          "Hours":"Sa'aatiiwwan",
          "F7":"F7",         
          "Action, Sci-fi":"Gocha, Sci-fi",
           "Price Details":"Bal'ina gatii",
          "Promo and Vochers":"Piroomoo fi Voochers",
          "Enter The promo code or voucher":"Koodii piroomoo ykn voocherii galchaa",
           "Cancel Booking":"Qabachuu dhiisaa",
           "Continoue To Payment":"Kaffatiitti fufaa",
           "First Name":"Maqaa jalqabaa",
           "Last Name":"Maqaa 2ffaa",
           "Remember me":"Na Yaadachiisaa",
           "I want to receive email":"Imeeliidhaanin barbaada",
            "Write a comment":"Yaada barreessaa",
           "Send":"Ergaa",
           "Alem Cinema":"Siniimaa Alem",
           "The trending cinema in Addis":"Siniimota finfinnee keessaa",
           "reviews":"2M daawwatame",
           "Upcoming Show":"Qophii Dhufu",
           "Today":"Har'a",
           "10:30 pm-12:00pm at \n Alem cinema":"10:30 PM - 12:PM Alem siniimaatti",
           "About Alem Cinema":"Waa'ee Alem siniimaa",
           "Welcome to Alem Cinema, a cinematic haven nestled in the heart of Ethiopia, where the magic of storytelling comes to life on the big screen. Alem Cinema stands as a beacon of entertainment, seamlessly blending modernity with Ethiopian cultural richness, offering an immersive cinematic experience like no other.\nAs you step through the doors of Alem Cinema, you are welcomed by an inviting ambiance that reflects the warmth and vibrancy of Ethiopian hospitality.":"Baga gara Alem Cinema, bakka sinimaa onnee Itoophiyaa keessatti argamu, bakka sihiina seenaa himuu iskiriinii guddaa irratti jireenyatti deebi'utti dhuftan. Alem Cinema akka ibsaa bashannanaatti dhaabbatee, ammayyummaa badhaadhina aadaa Habashaa waliin haala wal hin tuqneen walitti makuun, muuxannoo sinimaa nama liqimsu akka kan biraatti dhiheessa.\nAkkuma balbala Alem Cinema keessa tarkaanfattu, haala affeerraa ho'aa fi sochii calaqqisuun si simata keessummeessitoota Itoophiyaatti",
           "Show Less":"Xiqqaa Agarsiisi",
           "Load More":"Hunda Agarsiisi",
           "Come Visit Us":"Kottaa nu daawwadhaa",
           "XQRP+68P, Airport Road Addis Ababa":"XQRP+68P, Daandii Xiyyaaraa, Finfinnee",
           "Check our official Page":"Weebsaayitee keenyaa daawwadhaa",
           "Send to your phone":"Lakkoofsa bilbilaa keessan ergaa",
           "What people say about us":"Namootni waa'ee keenya maal jedhu",
           "Rate Our Cinema":"Siniimaa keenyaa madaalaa",
           "Tell others what you think":"Namoota biraallee affeeraa",
           "Rating and reviews are verified and are from people who use the service":"Sadarkaa fi gamaaggamni kan mirkanaa'ee fi namoota tajaajilicha fayyadaman irraa kan argamedha",
           "Write a review":"Gamaaggama barreessi",
           "Where do you want to go":"Eessa deemuu barbaaddu?",
          "Event":"Taatee",
          "Theatre":"Tiyaatira",
          "Home":"Mana",
          "Search":"Barbaadi",
          "Explore":"Alooli",
          "Person":"Nama",
          "Create new password":"Iggita haaraa uumaa",
          "Create your new password make sure it contains 6 characters, numbers, and special symbols":"Iggita haaraa kee uumi arfiilee 6, lakkoofsota, fi mallattoo addaa akka of keessaa qabu mirkaneessi",
          "New Password":"Iggita haaraa",
          "Confirm new password":"Iggita haaraa mirkaneessi",
          "Confirm Password":"Iggita mirkaneessi",
          "Passwords do not match":"Iggitni wal-simataa miti",
          "Continue":"Itti-fufi",
          "Reset Password Successful":"Iggitni keessan haqameera",
          "OK":"Tole",
          "Invalid index":"Kasaa dogoggoraa",
          "OTP Code Verification":"Mirkaneessa Koodii OTP",
          "We have sent an OTP code to your email mar********ley@yourdomain.com Enter the OTP code below to verify":"Koodii otp imeelii mar********ley@yourdomain.com kanarratti isiniif ergine galchaa",
          "Didn't receive email?":"Imeeliin isin hin qaqqabnee?",
          "You can resend code in":"Erra deebi'aa ergaa",
          "Reset Your Password":"Iggita keessan balleessaa",
          "Please enter your email, and we will send an OTP code in the next step to reset your password.":"Maaloo email keessan galchaa, tarkaanfii itti aanu keessatti koodii OTP ergina iggita keessan deebifnee saaguuf.",
          "Art":"Aartii",
         
          "News paper":"Waraqaa oduu",
          "Documentation":"Dokumantarii",
          "Horor":"Naasisaa",
          "10:30 PM - 12:PM at\n Alem Cinema":"10:30 PM - 12:PM Alem siniimaatti",         
          "Choose Seats":"Teessoo filadhaa",
          "Available":"Kan jiru",
          "Token":"Tokenii",
          "Selected":"Filatameera",
          "Total Price":"Gatii walii dalaa",
          "Seats":"Teessoowwan",
          "Personal Info":"Odeeffannoo dhuunfaa",
          "User Name":"Maqaa maammilaa",
          "Enter User Name":"Maqaa maammilaa galchaa",
          "Phone Number":"Lakkoofsa bilbilaa",
          "Enter Phone Number":"Lakkoofsa bilbilaa galchaa",
          "Gender":"Saala",
          "Male":"Dhiira",
          "Female":"Dhalaa",
          "Other":"Kan biraa",
          "Save":"kaa'aa",
          "Biometric ID":"Id Baayoomeetirikii",
          "Face ID":"ID Fuulaa",
          "SMS Authentication":"Mirkaneessa EEG",
          "Google Authentication":"Mirkaneessa Googilii",
          "Device Management":"To'annaa meeshaalee",
          "Change Password":"Iggita Jijjiiraa",
          "New Update Available! Update Movier and get a better cinematic experience \nat 09:40 AM.":"Fooyya'iinsi Haaraa Ni Argama! fiilmessaa haaromsi muuxannoo siniimaa fooyya'aa argadhu \n 09:40 AM",
          "Deadpol will be playing this afternoon at vadmad cinema \nat 09:40 AM.":"Deadpol har'a waaree booda vadmad cinema keessatti ni taphata \n 09:40 AM.",
          "Yesterday":"Kaleessaa",
          "About Movie":"Waa'ee fiilmii",
          "About us":"Waa'ee keenya",
          "Privacy and Policy":"Dhuunfaa fi Imaammata",
          "Contact Us":"Nu qunnamaa",
          "Partner":"Miiltoo",
          "Accessibility":"Dhaqqabummaa",
          "Feedback":"Feesbookii",
          "Rate Us":"Nu madaalaa",
          "Visit Our Website":"Weebsaayitii keenya daawwadhaa",
          "Follow Us On Social Media":"Miidiyaa Hawaasaa Irratti Nu Hordofaa",
          "Add Payment":"Kaffaltii Dabalaa",
          "Card Number":"Lakkoofsa kaardii",
          "Account Holder Name":"Maqaa Abbaa Herregaa",
          "Beth Abraham":"Beetii Abraham",
          "Expire Date":"Guyyaa Xumuraa",
          "Choose Payment Method":"Kaffaltii filadhaa",
          "Select Payment Method":"Mala Kaffaltii filadhaa",
          "Please select a payment method before proceeding.":"Maaloo itti fufuu kee dura mala kaffaltii filadhu.",
          "Add New Payment":"Kaffaltii dabalaa",
          "Confirm Payment":"Kaffaltii mirkaneessaa", 
          "Are you sure you want to confirm the payment of \$680.00?":"Kaffaltii \$680.00 ni mirkaneessituu?",
          "Cancel":"Dhiisaa",
          "Confirm":"Mirkaneessaa",
          "Contact us":"Nu qunnamaa",
          "Call":"Bilbilaa",
          "Facebook":"Feesbuukii",
          "Linkedin":"Linkidiinii",
          "Choose Cinema":"Siniimaa filadhaa",
          "Your location":"Argama keessan",
          "Addis Ababa":"Finfinnee",
          "All Cinema":"Siniimaa hunda",
          "Favorite":"Jaallatamaa",
          
          "Order Details":"Ajaja gadi-fageenyaan",
          "Jumbo Popcorn":"Jaamboo fandiishaa",
          "Indulge in the ultimate movie experience with our movie magic popcorn":"Muuxannoo fiilmii isa dhumaa kan fiilmii sihiina fandiishaa keenyaa wajjin of kennuu",
          "Note for your food  or drinks":"Yaadannoo nyaataa fi dhugaatii",
          "Leave notes here":"Yaada keessan katabaa",
          "Add to basket":"Boorsaatti dabali",
          "Food and Order":"Nyaataa fi ajaja",
          "Most Popular":"Beekamaa",
          "View All":"Hunda ilaalaa", 
          "Burger and Chips":"bargarii fi chiipsii",
          "How to report cinema issues?":"Dhimma siniimaa \nakkamitti gabaasuu dandeenya?",
          "Can I book my tickets once?":"Altokkotti tikeetii\n qabachuu nan danda'aa?",
          "How to cancel or refund tickets?":"Akkaiin dhiisu ykn irra deebi'u?",
          "Can I modify booking?":"Fooyyessuu nan danda'aa",
          "How do I book tickets?":"Akkamiin qabadhu?",
          "What is movier?":"Fiilmiin maali?",
          "Search...":"barbaadi...",
          "Payment":"Kaffaltii",
          "Account":"Herreda",
          "Help Center":"Giddugala Gargaarsaa",
          "Romance":"jaalalaa",
          "Mystery":"Dhoksaa",
          "Science Fiction":"Asoosama Saayinsii",
          "Thriller":"Hawwataa",
          "Crime":"Yakka",
          "Western":"Warreen-lixaa",
          "Sports":"Ispoortii",
          "Adventure":"Sodaachisaa",
          "Musical":"Muuziqaa",
          "Historical":"Seenaa",
          "Travel":"Deemsa",
          "Biographical":"Baayiloogikaalii",
          "Psychological":"Saayikoloogikaalii",
          "Family":"Maatii",
          "Supernatural":"Uumamaa ol",
          "Zombie":"Zoombii",
          "Drama":"Diraamaa",
          "Martial Arts":"Agarsiisa faayoo",
          "War":"Waraana",
          "Order Summary":"Order Summary",
          "Pick up time":"Yeroo filadhaa filadhaa",
          "You need to choose your time'":"Yeroo mataa keessanii filadhaa'",
          "Jumbo popcorn(x1)":"Jaamboo fandiishaa(x1)",
          "Service Fee":"Kaffaltii Tajaajilaa",
          "Actual Pay":"Kaffaltii Dhugaa",                          
          "Purchase and pick up of food or drinks can only be done on the same day.\n\n":"Nyaata ykn dhugaatii bitachuu fi fudhachuun guyyaa tokkotti qofa raawwatamuu danda'a.\n\n",
          "If you order food or drinks to watch a movie, we recommend picking it up 10 minutes before the movie starts.":"Fiilmii ilaaluuf nyaata ykn dhugaatii yoo ajajtan, fiilmiin jalqabuu isaa daqiiqaa 10 dura akka fudhattan isin gorsina.",
          "The privacy and policies related to online cinema ticket booking can vary among different platforms and service providers. However, there are common elements that are typically addressed in such policies. Here are some general aspects you might find in the privacy and policies of online cinema ticket booking platforms:":"Iccitii fi imaammattoonni tikkeettii sinimaa toora interneetii irratti buufachuu wajjin walqabatan waltajjiiwwan adda addaa fi tajaajila kennitoota gidduutti garaagarummaa qabaachuu danda’u. Haa ta’u malee, imaammata akkasii keessatti wantootni waliigalaa akkaataa adda addaatiin ilaalaman jiru. Iccitii fi imaammata waltajjiiwwan tikkeettii sinimaa toora interneetii irratti buufachuu keessatti wantoota waliigalaa argachuu dandeessan tokko tokko kunooti:",
          "Personal Information Collection":"Odeeffannoo Dhuunfaa Walitti Qabuu",
          "The policies usually outline what types of personal information will be collected during the booking process. This may include details such as your name, contact information, payment details, and sometimes demographic information.":"Imaammattoonni yeroo baay’ee adeemsa buukii keessatti odeeffannoo dhuunfaa gosa akkamii akka walitti qabamu ibsu. Kunis ibsa bal’aa kan akka maqaa kee, odeeffannoo quunnamtii, ibsa kaffaltii, fi yeroo tokko tokko odeeffannoo dimogiraafii of keessatti qabachuu danda’a.",
          "Data Usage":"Fayyadama daataa",
          "Platforms typically specify how they will use the collected information. This can include processing your ticket orders, sending you relevant notifications, and possibly using the data for marketing purposes.":"Waltajjiiwwan akkaataa idileetti odeeffannoo walitti qabame akkamitti akka fayyadaman ibsu. Kunis ajaja tikkeettii keessanii adeemsisuu, beeksisa barbaachisaa ta’e isiniif erguu, fi tarii daataa sana kaayyoo gabaaf fayyadamuu dabalatee ta’uu danda’a.",
          "Security Measures":"Tarkaanfiiwwan Nageenyaa",
          "The policies often describe the security measures in place to protect your personal information. This may include encryption methods for sensitive data and secure payment gateways.":"Imaammattoonni yeroo baay’ee tarkaanfiiwwan nageenyaa odeeffannoo dhuunfaa keessan eeguuf fudhataman ibsu. Kunis malawwan icciitii deetaa miiraa fi karra kaffaltii nageenya qabuu of keessatti qabachuu danda’a.",
          "Cookies and Tracking":"Kuukii fi tikkeettii",
          "Platforms may use cookies or other tracking technologies to enhance user experience and gather information about website usage. The policies usually explain the purpose of such technologies and how you can manage your preferences.":"Waltajjiiwwan muuxannoo fayyadamaa fooyyessuu fi waa’ee itti fayyadama weebsaayitii odeeffannoo walitti qabuuf kukii ykn teeknooloojiiwwan hordoffii biroo fayyadamuu danda’u. Imaammattoonni yeroo baay’ee kaayyoo teeknooloojiiwwan akkasii fi akkaataa filannoo kee bulchuu dandeessu ibsu.",
          "Third-Party Sharing":"Qoodinsa qaamaa 3ffaa",
          "The policies often state whether the platform shares your information with third parties. This can include sharing data with cinema partners or other service providers.":"Imaammattoonni yeroo baayyee waltajjiin odeeffannoo keessan qaama sadaffaaf qooduu fi dhiisuu isaa ibsu. Kunis michoota sinimaa ykn tajaajila kennitoota biroo waliin daataa qooduu dabalatee ta’uu danda’a.",
          "Retention Period":"Yeroo Tursiisaa",
          "Platforms usually specify how long they will retain your personal information. This can vary depending on legal requirements and business needs.":"Waltajjiiwwan yeroo baay’ee odeeffannoo dhuunfaa kee hanga yoomitti akka qabatan ibsu. Kunis ulaagaalee seeraa fi fedhii daldalaa irratti hundaa’uun garaagarummaa qabaachuu danda’a.",
          "User Rights":"Mirga Fayyadamtootaa",
          "Your rights regarding your personal information are often outlined in the policies. This may include the right to access, correct, or delete your data.":"Odeeffannoo dhuunfaa kee ilaalchisee mirgi kee yeroo baay’ee imaammata keessatti ibsameera. Kunis mirga daataa kee argachuu, sirreessuu ykn haquu dabalatee ta’uu danda’a.",
          "Legal Compliance":"Seerawaa",
          "Platforms typically outline their commitment to complying with relevant data protection laws and regulations.":"Waltajjiiwwan akkaataa idileetti seeraa fi dambiiwwan eegumsa daataa barbaachisoo ta’an kabajuuf waadaa galanii ibsu.",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platform customer support for clarification":"Akkaataa daataa keessan itti qabamu hubachuu fi waa’ee tajaajilicha fayyadamuu irratti murtoo sirrii ta’e murteessuuf imaammata icciitii waltajjii tikkeettii sinimaa toora interneetii addaa buufachuu fayyadamtan of eeggannoodhaan dubbisuun barbaachisaa dha. Yoo yaaddoo ykn gaaffii addaa qabaatte, ibsa argachuuf deeggarsa maamiltoota waltajjii sanaas dhaquu dandeessa",
          "Old Password":"Paswordii duraanii",
          "New":"Haarawaa",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you are using to ensure you understand how your data is being handled and to make an informed decision about using the service. If you have specific concerns or questions, you may also reach out to the platforms customer support for clarification":"Akkaataa daataa keessan itti qabamu hubachuu fi waa’ee tajaajilicha fayyadamuu irratti murtoo sirrii ta’e murteessuuf imaammata icciitii waltajjii tikkeettii sinimaa toora interneetii addaa buufachuu fayyadamtan of eeggannoodhaan dubbisuun barbaachisaa dha. Yoo yaaddoo ykn gaaffii addaa qabaattan, ibsa argachuuf deeggarsa maamiltoota waltajjiiwwaniis bira gahuu dandeessu",
          "Watched":"Daawwatameera",
          "Booking Confirmation":"Bakka mirkaneeffadhaa",
          "Cinema Rating":"Sadarkaa Siniimaa",
          "Order Update":"Fooyya'insa Ajajaa",
          "Seat Availability Alert":"Teessoowwan jiran",
          "Ticket Reminder":"Yaadachiisa Tikkeettii",
          "Connected":"Walitti hidhame",
          "Confirm Payment-\$680.00":"Kaffaltii Mirkaneessaa-\$680.00",
          "Release date":"Guyyaa Gadhiifamu",
          "Age":"Umurii",
          "Rating":"Sadarkaa kennaa",
          "Location":"Bakka",
          "Amharic":"Amharic",
          "Afaan Oromoo":"Afaan Oromoo",
          "Tigrigna":"Tigrigna",
          "Forgot password?":"Iggita dagattanii?",
          "Not a member?":"Miseensa mitii?",
         "Trending filters":"Ilaaluun adda baasaa",
          "Filter by":"Adda baasaa",
          "Search A movie":"Fiilmii barbaadi",
          "Time:":"Yeroo:",
          "Date:":"Guyyaa:", 
          "Enter Password": "Iggita galchaa",         
          "10:30 pm-12:00 pm at Alem cinema": "10:30 pm-12:00 pm mana sinimaa Alem keessatti",     
         "9:30 pm-11:00 pm at Ednamol cinema": "Halkan sa'aatii 9:30-11:00tti mana sinimaa Ednamol keessatti",
          "3:20 am-11:00 am At cinema": "3:20 am-11:00 am Sinimaa irratti",
          "Nearby Theatre":"Tiyaatira dhiyoo jiru",
          "enter location:":"bakka galchi"
         
        },
        "ti": {
          "Welcome to\nmovie booker": "እንቋዕ ናብ ፊልም ቡከር ብደሓን መጻእኩም",
          "Discover and book cinema tickets with ease": "ትኬት ሲነማ ብቐሊሉ ርኸቡን ምዝገባ ግበሩን",
          "Log in": "እቶ",
          "User Name": "ስም ተጠቃሚ",
          "Email": "ኢመይል",
          "Password": "መሕለፊ ቓል",
          "Remember me": "ዘክሩኒ",
          "I want to recieve email": "ኢመይል ክቕበል ደልየ ኣለኹ",
          "Sign Up": "ተመዝገብ",
          "Enter User Name": "ስም ተጠቃሚ ኣእቱ",
          "Enter Email": "ኢመይል ኣእትዉ",
          "Enter Password": "ኣእትዉ መሕለፊ ቓል",
          "Not a member?": "ኣባል ኣይኮነን?",
          "If you order food or drinks to watch a movie, we recommend picking it up 10 minutes before the movie starts.": "ፊልም ንምርኣይ መግቢ ወይ መስተ እንተ ኣዚዝኩም፡ ቅድሚ ፊልም ምጅማሩ 10 ደቓይቕ ክትወስዶ ንመክር።",
          "Forgot password?":"ፓስዎርድ ረሲዕካ?",
          "Continue To Payment":"ናብ ክፍሊት ምቕጻል",
          "Yes Logout": "እወ ኣውት ኣውት",          
          "Are you sure you want to logout?": "ርግጸኛ ዲኻ ክትወጽእ ከም እትደሊ?",          
          "Join now": "ሕጂ ተጸንበሩ",
          "Continue as a guest": "ከም ጋሻ ቀጽል",
          "Ethio Cinema": "ኢትዮ ሲነማ",
           "Where do you want to go?":"ናበይ ክትከይድ ትደሊ?",
          "200 meters away": "200 ሜትሮ ርሒቑ",
          "Second Cinema": "ካልኣይ ሲነማ",
          "meters away 300": "300 ሜትሮ ርሒቑ",
          "Discover movies and book tickets": "ፊልምታት ርኸቡን ትኬት ምዝገባ ግበሩን",
          "enter movie or cinema": "ፊልም ወይ ሲነማ ምእታው",
          "Nearby cinema": "ኣብ ቀረባ ዝርከብ ሲነማ",
          "More": "ቡዙሕ",
          "Genres": "ቅዲታት",
          "Comedy": "ኮሜዲ",
          "Fantasy": "ፍንጣጣ",
          "Action": "ተግባር",
          "Horror": "ራዕዲ",
          "Documentary": "ሰነዳዊ ፊልም",
          "Coming of the robot": "ምምጻእ ናይቲ ሮቦት",
          "Coming of the Robot": "ምምጻእ ናይቲ ሮቦት",
          "Watch": "ተመልከት",
          "Genre": "ወግዒ",
          "10:30 pm-12:00 pm at Alem cinema": "ካብ ሰዓት 10፡30 ድሕሪ ቀትሪ-12፡00 ድሕሪ ቀትሪ ኣብ ሲነማ ኣለም",
         "9:30 pm-11:00 pm at Ednamol cinema": "ካብ ሰዓት 9፡30 ድሕሪ ቀትሪ-11፡00 ድሕሪ ቀትሪ ኣብ ሲነማ ኤድናሞል",
          "3:20 am-11:00 am at At cinema": "3፡20 ንግሆ-11፡00 ንግሆ ኣብ ኣብ ሲነማ",
          "Sci_fi": "ሳይንሳዊ ፍጻመ",
          "Price": "ዋጋ",
          "Showtime": "ናይ ምርኢት ግዜ",
          "Description": "መግለፂ",
          "In a not-so-distant future, society teeters on the brink of chaos as a brilliant scientist unleashes a groundbreaking artificial intelligence. A task force is deployed to control the evolving situation. What ensues is a 	high-stakes game of cat and mouse, where humanity fate hangs in the balance.": "ኣብ ብዙሕ ርሑቕ ዘይኮነ መጻኢ፡ ሓደ ንፉዕ ሳይንቲስት መሰረት ዝሰበረ ኣርቲፊሻል ኢንተለጀንስ ኣብ ዝለቐቐሉ እዋን፡ ሕብረተሰብ ኣብ ኣፍደገ ህውከት ይንቀሳቐስ። ነቲ ዝምዕብል ዘሎ ኩነታት ንምቁጽጻር ሓይሊ ዕማም ይውፈር። እቲ ዝስዕብ ድማ ዕጫ ወዲ ሰብ ኣብ ሚዛን ዝንጠልጠለሉ ልዑል ዋጋ ዘለዎ ጸወታ ድሙን ኣንጭዋን እዩ",          
          "In to the purple":"ኣብ ናብቲ ሐምላይ",
          "Green the grinch":"ነቲ ግሪንች ሓምላይ",
          "little the red boot":"ንእሽቶ እታ ቀይሕ ቦት",
          "Dino dog":"ዲኖ ከልቢ",
          "Freaky flamingo":"ፍሪኪ ፍላሚንጎ",
          "enter movie":"ፊልም ኣእትዉ",
          "Animation":"ኣኒሜሽን",
          
          "Movier v5.7.8": "ሞቪየር v5.7.8",
        
          "Enter valid email":"ቅኑዕ ኢመይል ኣእቱ",
          
          "Enter password":"ፓስዎርድ ኣእቱ",
          "Forgot password":"ፓስዎርድ ረሲዐዮ",
          "Log In":"መእተዊ",
          "Not a member":"ኣባል ኣይኮነን",
          
          "seat":"ኮፍ ምባል",
	"250/seat":"250/ኮፍ ምባል",
          "English":"English",
          "Mark":"ማርቆስ",
          "Fav Cinema":"ፋቭ ሲነማ",
          "Movie Interest":"ፊልም ተገዳስነት",
          "Payment Method":"ኣገባብ ክፍሊት",
          "Generals":"ጀነራላት",
          "Personal info":"ውልቃዊ ሓበሬታ",
          "Notification":"መፍለጢ",
          "Security":"ድሕንነት",
          "Language":"ቋንቋ",
          "Dark mode":"ጸሊም ሞድ",
          "About":"ብዝዕባ",
          "Help center":"ማእከል ሓገዝ",
          "About_us":"ብዛዕባና",
          "Logout":"ኣውት ኣውት",
          "Select Language":"ቋንቋ ምረጽ",
           "Review Summary":"ጽማቕ ገምጋም",
          "Duration":"ጻንሒት",
          "128 minutes":"128 ደቒቓታት",
          "Director":"ዳይሬክተር",
          "Nahome":"ናሆመ",
          "AR":"AR",
          "R17":"R17",
          "Booking Details":"ዝርዝር ምዝገባ",
          "Cinema":"ሲነማ",
          "AMC Emp 25":"AMC Emp 25",
          "Package":"ጥቕላል",
          "Standart":"መለክዒ",
          "Auditorium":"ኣዳራሽ",
          "Auditorium 3":"ኣዳራሽ 3",
          "Date":"ዕለት",
          "Feb 28, 2024":"28 ለካቲት 2024 ዓ.ም",
          "Hours":"ሰዓታት",
          "F7":"F7",  
          "Jumbo Popcorn":"ጃምቦ ፖፕኮርን",     
          "Action, Sci-fi":"ተግባር፣ ሳይንሳዊ ፍጻመ",
           "Price Details":"ዝርዝር ዋጋ",
          "Promo and Vochers":"ፕሮሞን ቮቸርን \nዝበሃሉ ምዃኖም ይፍለጥ",
          "Enter The promo code or voucher":"ፕሮሞ ኮድ ወይ ቫውቸር ኣእትዉ",
           "Cancel Booking":"ምዝገባ ስርዝ ድልዝ",
           "First Name":"ናይ መጀመርታ ሽም",
           "Last Name":"ናይ መወዳእታ ሽም",
           
           "I want to receive email":"ኢመይል ክቕበል ደልየ ኣለኹ",
            "Write a comment":"ርእይቶ ጽሓፉ",
           "Send":"ስደድ",
           "Alem Cinema":"ኣለም ሲነማ",
           "The trending cinema in Addis":"ኣብ ኣዲስ ትረንድ ዝኾነ ሲነማ",
           "2M reviews":"2M ሪኢቶታት",
           "Upcoming Show":"ኣብ ዝመጽእ መደብ",
           "Today":"ሎምዓንቲ",
           "10:30 pm-12:00pm at \n Alem cinema":"ካብ ሰዓት 10፡30 ድሕሪ ቀትሪ-12፡00 ድሕሪ ቀትሪ ኣብ \n ኣለም ሲነማ",
           "About Alem Cinema":"ብዛዕባ ኣለም ሲነማ",
           "Welcome to Alem Cinema, a cinematic haven nestled in the heart of Ethiopia, where the magic of storytelling 		comes to life on the big screen. Alem Cinema stands as a beacon of entertainment, seamlessly blending 			modernity with Ethiopian cultural richness, offering an immersive cinematic experience like no other.\nAs 		you step through the doors of Alem Cinema, you are welcomed by an inviting ambiance that reflects the warmth 		and vibrancy of Ethiopian hospitality.":"እንቋዕ ናብ ኣለም ሲነማ ብሰላም መጻእኩም፣ ኣብ ማእከል ኢትዮጵያ ተሰዂዑ ዘሎ ናይ ሲነማ መዕቆቢ፣ ስሕበት ምዝንታው ዛንታ ኣብ ዓቢ ስክሪን ህያው ዝኾነሉ። ኣለም ሲነማ ከም መብራህቲ መዘናግዒ ደው ኢሉ፣ ዘመናዊነት ምስ ባህላዊ ሃብቲ ኢትዮጵያ ብዘይ ገለ ጸገም ብምውህሃድ፣ ካልእ ዘይመስል ምጥሓል ሲነማዊ ተመኩሮ የቕርብ።\nብማዕጾታት ኣለም ሲነማ ክትረግጽ ከለኻ፣ ነቲ ውዑይን ንቕሓትን ዘንጸባርቕ ዕድመ ዝህብ ሃዋህው ይቕበልካ ናይ ኢትዮጵያዊ ኣቀባብላ ኣጋይሽ።",
           "Show Less":"ውሑድ ኣርእዩ",
           "Load More":"ተወሳኺ ጽዓኑ",
           "Come Visit Us":"ንዑ በጽሑና",
           "XQRP+68P, Airport Road Addis Ababa":"XQRP+68P, መንገዲ መዕርፎ ነፈርቲ ኣዲስ ኣበባ",
           "Check our official Page":"ወግዓዊ Pageና ተወከሱ",
           "Send to your phone":"ናብ ስልክኹም ስደዱ",
           "What people say about us":"ሰባት ብዛዕባና እንታይ ይብሉ",
           "Rate Our Cinema":"ንሲነማና ደረጃ ሃቡ",
           "Tell others what you think":"ንኻልኦት ዝሓሰብካዮ ንገሮም",
           "Rating and reviews are verified and are from people who use the service":"ደረጃን ገምጋምን ዝተረጋገጸ ኮይኑ ካብ ነቲ ኣገልግሎት ዝጥቀሙ ሰባት እዩ",
           "Write a review":"ክለሳ ጽሓፉ",
          "Event":"ዝግጅት",
          "Theatre":"ትያትር",
          "Home":"ገዛ",
          "Search":"ምድላይ",
          "Explore":"ዳህሰሳ",
          "Person":"ሰብ",
          "Create new password":"ሓድሽ ምልክት ቃል ምፍጣር",
          "Create your new password make sure it contains 6 characters, numbers, and special symbols":"ሓድሽ ምልክት ቃልካ ምፍጣር 6 ፊደላት፣ ቁጽርታትን ፍሉያት ምልክታትን ከም ዘለዎ ኣረጋግጽ",
          "New Password":"ሓድሽ ፓስዎርድ",
          "Confirm new password":"ሓድሽ ምልክት ቃል ኣረጋግጽ",
          "Confirm Password":"ሓድሽ ምልክት ቃል ኣረጋግጽ",
          "Passwords do not match":"ፓስዎርድታት ኣይሰማምዑን እዮም",
          "Continue":"ቀፃሊ",
          "Reset Password Successful":"ሪሰት ፓስዎርድ ዕዉት እዩ",
          "OK":"እሺ",
          "Invalid index":"ዘይሕጋዊ ኢንዴክስ",
          "OTP Code Verification":"ምርግጋጽ ኮድ ኦቲፒ",
          "We have sent an OTP code to your email mar********ley@yourdomain.com Enter the OTP code below to verify":"ናብ ኢመይልኩም mar********ley@yourdomain.com ናይ OTP ኮድ ሰዲድና ኣለና ንምርግጋጽ ኣብ ታሕቲ ዘሎ OTP ኮድ ኣእትዉ",
          "Didn't receive email?":"ኢመይል ኣይተቐበለን ድዩ?",
          "You can resend code in":"ኮድ ዳግማይ ክትሰድድ ትኽእል ኢኻ",
          "Reset Your Password":"ፓስዎርድካ ዳግማይ ኣቐምጦ",
          "Please enter your email, and we will send an OTP code in the next step to reset your password.":"በጃኹም ኢመይልኩም ኣእትዉ፡ ኣብ ዝቕጽል ስጉምቲ ድማ ፓስዎርድኩም ዳግማይ ንምስራዕ OTP ኮድ ክንሰድድ ኢና።",
          "Art":"ጥበብ",         
          "News paper":"ዜናዊ ወረቐት",
          "Documentation":"ሰነድ ምግባር",
          "Horor":"ራዕዲ",
          "10:30 PM - 12:PM at\n Alem Cinema":"10፡30 ድሕሪ ቀትሪ - 12:ድ.ቀ ኣብ\n ኣለም ሲነማ",         
          "Choose Seats":"መንበር ምረጽ",
          "Available":"ቅሩብ",
          "Token":"ቶከን",
          "Selected":"ተመሪጹ",
          "Total Price":"ጠቕላላ ዋጋ",
          "Seats":"መንበር",
          "Personal Info":"ውልቃዊ ሓበሬታ",
          "Phone Number":"ቁጽሪ ተሌፎን",
          "Enter Phone Number":"ቁጽሪ ተሌፎን ኣእትዉ",
          "Gender":"ፆታ",
          "Male":"ተባዕታይ",
          "Female":"ኣንስተይቲ",
          "Other":"ካልእ",
          "Save":"ምቑጣብ",
          "Biometric ID":"ባዮሜትሪክ መለለዪ መንነት",
          "Face ID":"ናይ ገጽ መለለዪ",
          "SMS Authentication":"ናይ ኤስኤምኤስ ምርግጋጽ",
          "Google Authentication":"ናይ ጉግል ምርግጋጽ",
          "Device Management":"ምሕደራ መሳርሒ",
          "Change Password":"ፓስዎርድ ምቕያር",
          "New Update Available! Update Movier and get a better cinematic experience \nat 09:40 AM.":"ሓድሽ እዋናዊ ሓበሬታ ተዳልዩ ኣሎ! ንሞቪየር ኣዘምን ዝሓሸ ናይ ሲነማ ተመኩሮ ረኸብ \nat 09:40 AM.",
          "Deadpol will be playing this afternoon at vadmad cinema \nat 09:40 AM.":"ዲድፑል ሎሚ ድሕሪ ቀትሪ ኣብ vadmad ሲነማ \n ሰዓት 09:40 AM ክጻወት እዩ።",
          "Yesterday":"ትማሊ",
          "About Movie":"ብዛዕባ ፊልም",
          "About us":"ብዛዕባና",
          "Privacy and Policy":"ብሕታዊነትን ፖሊሲን",
          "Contact Us":"ርኸቡና",
          "Partner":"መሳርሕቲ",
          "Accessibility":"ተበጻሕነት",
          "Feedback":"ርእይቶ",
          "Rate Us":"ደረጃ ሃቡና",
          "Visit Our Website":"ኣብ መርበብ ሓበሬታና ተወከሱ",
          "Follow Us On Social Media":"ኣብ ማሕበራዊ ሚድያ ተኸታተሉና",
          "Add Payment":"ክፍሊት ምውሳኽ",
          "Card Number":"ቁጽሪ ካርድ",
          "Account Holder Name":"ስም ወናኒ ሕሳብ",
          "Beth Abraham":"ቤት ኣብርሃም",
          "Expire Date":"ናይ ምውዳእ ዕለት",
          "Choose Payment Method":"ኣገባብ ክፍሊት ምረጽ",
          "Select Payment Method":"ኣገባብ ክፍሊት ምረጽ",
          "Please select a payment method before proceeding.":"ቅድሚ ምቕጻልኩም ኣገባብ ክፍሊት ምረጹ",
          "Add New Payment":"ሓድሽ ክፍሊት ምውሳኽ",
          "Confirm Payment":"ክፍሊት ኣረጋግጽ", 
          "Are you sure you want to confirm the payment of \$680.00?":"ርግጸኛ ዲኻ ክፍሊት \$680.00 ከተረጋግጽ ትደሊ?",
          "Cancel":"ሰርዝ",
          "Confirm":"ኣረጋግፅ",
          "Contact us":"ርኸቡና",
          "Call":"ደውል",
          "Facebook":"ፌስቡክ",
          "Linkedin":"ሊንክዲን",
          "Choose Cinema":"ሲነማ ምረጽ",
          "Your location":"ኣቀማምጣኻ",
          "Addis Ababa":"ኣዲስ ኣበባ",
          "All Cinema":"ኩሉ ሲነማ",
          "Favorite":"ባህጊ",
          "Order Details":"ዝርዝር ትእዛዝ",
          
          "Indulge in the ultimate movie experience with our movie magic popcorn":"ኣብ ናይ መወዳእታ ናይ ፊልም ተመኩሮ ምስ ናይ ፊልም ማጂክ ፖፕኮርንና ተሓጐሱ",
          "Note for your food  or drinks":"ንመግቢ ወይ መስተኻ ኣስተውዕል",
          "Leave notes here":"ኣብዚ መዘኻኸሪታት ግደፉ",
          "Add to basket":"ኣብ መሶብ ወስኹሉ",
          "Food and Order":"መግብን ስርዓትን",
          "Most Popular":"ዝያዳ ተፈታዊ",
          "View All":"ንኹሉ ርአ", 
          "Burger and Chips":"በርገርን ቺፕስን",
          "How to report cinema issues?":"ጉዳይ ሲነማ ብኸመይ ንሕብር?",
          "Can I book my tickets once?":"ትኬተይ ሓንሳብ ክሕዝ ይኽእል ድየ?",
          "How to cancel or refund tickets?":"ትኬት ብኸመይ ንስርዞ ወይ ንመልሶ?",
          "Can I modify booking?":"ምዝገባ ክቕይር ይኽእል ድየ?",
          "How do I book tickets?":"ከመይ ጌረ ትኬት ይሕዝ?",
          "What is movier?":"ፊልም እንታይ እዩ?",
          "Search...":"ምድላይ...",
          "Payment":"ክፍሊት",
          "Account":"ኣካውንት",
          "Help Center":"ማእከል ሓገዝ",
          "Romance":"ፍቕራዊ ዛንታ",
          "Mystery":"ምሽጥር",
          "Science Fiction":"ሳይንሳዊ ልቢ ወለድ",
          "Thriller":"ትሪለር",
          "Crime":"ወንጀል",
          "Western":"ምዕራባውያን",
          "Sports":"ስፖርት",
          "Adventure":"ሰቓሊ ልቢ",
          "Musical":"ሙዚቃዊ",
          "Historical":"ታሪኻዊ",
          "Travel":"ምጉዓዝ",
          "Biographical":"ታሪኽ ህይወት",
          "Psychological":"ስነ-ልቦናዊ",
          "Family":"ስድራ",
          "Supernatural":"ልዕለ ባህርያዊ",
          "Zombie":"ዞምቢ",
          "Drama":"ድራማ",
          "Martial Arts":"ማርሻል ኣርትስ",
          "War":"ውግእ",
          "Order Summary":"ጽማቕ ትእዛዝ",
          "Pick up time":"ግዜ ኣልዕል",
          "You need to choose your time'":"ግዜኻ ክትመርጽ ኣለካ",
          "Jumbo popcorn(x1)":"ጃምቦ ፖፕኮርን(x1)",
          "Service Fee":"ናይ ኣገልግሎት ክፍሊት",
          "Actual Pay":"ጭቡጥ ክፍሊት",                          
          "Purchase and pick up of food or drinks can only be done on the same day.\n\n":"ምግዛእን ምውሳድን ምግቢ ወይ መስተ ኣብ ሓደ መዓልቲ ጥራይ እዩ ክግበር ዝኽእል።\n\n",
          "If you order food or drinks to watch a movie, we recommend picking it up 10 minutes before the movie 			starts.":"ፊልም ንምርኣይ መግቢ ወይ መስተ እንተ ኣዚዝኩም፡ ቅድሚ ፊልም ምጅማሩ 10 ደቓይቕ ክትወስዶ ንመክር።",
          "The privacy and policies related to online cinema ticket booking can vary among different platforms and service 		providers. However, there are common elements that are typically addressed in such policies. Here are some 		general aspects you might find in the privacy and policies of online cinema ticket booking 				platforms:":"ምስ ምሕዛዝ ትኬት ሲነማ ብኢንተርነት ዝተኣሳሰር ብሕታውነትን ፖሊሲታትን ኣብ መንጎ ዝተፈላለዩ መድረኻትን ወሃብቲ ኣገልግሎትን ክፈላለ ይኽእል። ይኹን እምበር፡ ኣብ ከምዚ ዝኣመሰለ ፖሊሲታት ብተለምዶ ዝድህሰሱ ልሙዳት ባእታታት ኣለዉ። ኣብ ብሕታዊነትን ፖሊሲታትን ናይ ኦንላይን ሲነማ ትኬት ምዝገባ መድረኻት ክትረኽብዎም እትኽእሉ ገለ ሓፈሻዊ መዳያት ኣብዚ ኣለዉ።",
          "Personal Information Collection":"ውልቃዊ ሓበሬታ ምእካብ",
          "The policies usually outline what types of personal information will be collected during the booking process. 		This may include details such as your name, contact information, payment details, and sometimes demographic 		information.":"መብዛሕትኡ ግዜ እቶም ፖሊሲታት ኣብ መስርሕ ምዝገባ እንታይ ዓይነት ውልቃዊ ሓበሬታ ከም ዝእከብ ይገልጹ። እዚ ከም ስምካ፡ ርክብ ሓበሬታኻ፡ ዝርዝር ክፍሊት፡ ሓደ ሓደ ግዜ ድማ ዲሞግራፊካዊ ሓበሬታ ዝኣመሰሉ ዝርዝራት ከጠቓልል ይኽእል።",
          "Data Usage":"ኣጠቓቕማ ዳታ",
          "Platforms typically specify how they will use the collected information. This can include processing your ticket 		orders, sending you relevant notifications, and possibly using the data for marketing 					purposes.":"መድረኻት ብተለምዶ ነቲ ዝተኣከበ ሓበሬታ ብኸመይ ከም ዝጥቀሙሉ ይገልጹ። እዚ ድማ ንናይ ትኬት ትእዛዛትካ ምምስራሕ፡ ኣገዳሲ መፍለጢታት ምልኣኽ፡ ምናልባት’ውን ነቲ ዳታ ንዕላማታት ዕዳጋ ምጥቃም ከጠቓልል ይኽእል።",
          "Security Measures":"ስጉምትታት ጸጥታ",
          "The policies often describe the security measures in place to protect your personal information. This may include 		encryption methods for sensitive data and secure payment gateways.":"እቶም ፖሊሲታት መብዛሕትኡ ግዜ ነቲ ውልቃዊ ሓበሬታኻ ንምሕላው ዝውሰድ ስጉምትታት ጸጥታ ይገልጹ። እዚ ድማ ንሃሳስ ዳታን ውሑስ ናይ ክፍሊት ኣፍደገታትን ዝኸውን ሜላታት ምስጢራዊ ምግባር ከጠቓልል ይኽእል።",
          "Cookies and Tracking":"ኩኪስን ምክትታልን",
          "Platforms may use cookies or other tracking technologies to enhance user experience and gather information about 		website usage. The policies usually explain the purpose of such technologies and how you can manage your 		preferences.":"መድረኻት ተመኩሮ ተጠቃሚ ንምዕባይን ብዛዕባ ኣጠቓቕማ መርበብ ሓበሬታ ሓበሬታ ንምእካብን ኩኪስ ወይ ካልእ ናይ ምክትታል ቴክኖሎጂታት ክጥቀሙ ይኽእሉ። እቶም ፖሊሲታት መብዛሕትኡ ግዜ ዕላማ ናይ ከምዚኦም ዝኣመሰሉ ቴክኖሎጂታትን ንምርጫታትካ ብኸመይ ከተመሓድር ከም እትኽእልን ይገልጹ።",
          "Third-Party Sharing":"ሳልሳይ ወገን ምክፋል",
          "The policies often state whether the platform shares your information with third parties. This can include 			sharing data with cinema partners or other service providers.":"እቶም ፖሊሲታት መብዛሕትኡ ግዜ እቲ መድረኽ ሓበሬታኻ ምስ ሳልሳይ ወገን የካፍል ድዩ ኣይካፈልን ይገልጹ። እዚ ድማ ምስ መሻርኽቲ ሲነማ ወይ ካልኦት ወሃብቲ ኣገልግሎት ዳታ ምክፋል ከጠቓልል ይኽእል።",
          "Retention Period":"ናይ ምዕቃብ ግዜ",
          "Platforms usually specify how long they will retain your personal information. This can vary depending on legal 		requirements and business needs.":"መብዛሕትኡ ግዜ መድረኻት ውልቃዊ ሓበሬታኻ ክሳብ ክንደይ ከም ዝዕቅቡ ይገልጹ። እዚ ከከም ሕጋዊ ጠለባትን ንግዳዊ ድሌታትን ክፈላለ ይኽእል።",
          "User Rights":"መሰል ተጠቃሚ",
          "Your rights regarding your personal information are often outlined in the policies. This may include the right to 		access, correct, or delete your data.":"ንውልቃዊ ሓበሬታኻ ዝምልከት መሰላትካ መብዛሕትኡ ግዜ ኣብቲ ፖሊሲታት ተዘርዚሩ ኣሎ። እዚ ድማ ዳታኻ ናይ ምርካብ፣ ምእራም ወይ ምድምሳስ መሰል ከጠቓልል ይኽእል።",
          "Legal Compliance":"ሕጋዊ ምኽባር",
          "Platforms typically outline their commitment to complying with relevant data protection laws and 				regulations.":"መድረኻት ብተለምዶ ምስ ዝምልከቶም ሕግታትን ስርዓታትን ሓለዋ መረዳእታ ንምኽባር ዘለዎም ተወፋይነት ይገልጹ።",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you 		are using to ensure you understand how your data is being handled and to make an informed decision about 		using the service. If you have specific concerns or questions, you may also reach out to the platform 			customer support for clarification":"ዳታኻ ብኸመይ ከም ዝሕዞ ንምርግጋጽን ብዛዕባ ኣጠቓቕማ እቲ ኣገልግሎት ብግቡእ ዝተሰነየ ውሳነ ንምውሳንን ናይቲ እትጥቀመሉ ዘለኻ ፍሉይ ናይ ኦንላይን ትኬት ትኬት ሲነማ ፖሊሲ ብጥንቃቐ ምንባብ ኣገዳሲ እዩ። ፍሉይ ስክፍታታት ወይ ሕቶታት እንተሃልዩካ፡ ንመብርሂ ናብቲ ናይ መድረኽ ደገፍ ዓማዊል እውን ክትበጽሕ ትኽእል ኢኻ።",
          "Old Password":"ናይ ቀደም ፓስዎርድ",
          "New":"ሓድሽ",
          "It is important to carefully read the privacy policy of the specific online cinema ticket booking platform you 		are using to ensure you understand how your data is being handled and to make an informed decision about 		using the service. If you have specific concerns or questions, you may also reach out to the platforms 			customer support for clarification":"ዳታኻ ብኸመይ ከም ዝሕዞ ንምርግጋጽን ብዛዕባ ኣጠቓቕማ እቲ ኣገልግሎት ብግቡእ ዝተሰነየ ውሳነ ንምውሳንን ናይቲ እትጥቀመሉ ዘለኻ ፍሉይ ናይ ኦንላይን ትኬት ትኬት ሲነማ ፖሊሲ ብጥንቃቐ ምንባብ ኣገዳሲ እዩ። ፍሉይ ስክፍታታት ወይ ሕቶታት እንተሃልዩካ፡ ንመብርሂ ናብ ደገፍ ዓማዊል መድረኻት እውን ክትበጽሕ ትኽእል ኢኻ።",
          "Watched":"ተዓዚብናዮ",
          "Booking Confirmation":"ምርግጋጽ ምዝገባ",
          "Cinema Rating":"ደረጃ ሲነማ",
          "Order Update":"ትእዛዝ እዋናዊ ሓበሬታ",
          "Seat Availability Alert":"መንበር ምህላው መጠንቀቕታ",
          "Ticket Reminder":"መዘኻኸሪ ትኬት",
          "Connected":"ዝተኣሳሰረ",
          "Confirm Payment-\$680.00":"ክፍሊት ኣረጋግጽ-\$680.00",
          "Release date":"ዕለት ምውጻእ",
          "Age":"ዕድመ",
          "Rating":"ደረጃ ምሃብ",
          "Location":"ኣንፈት",
          "Amharic":"ኣምሓርኛ",
          "Afaan Oromoo":"Afaan Oromoo",
          "Tigrigna":"ትግርኛ",
         "Trending filters":"ትሬንዲንግ ፍልትራት",
          "Filter by":"ብ ፍልፍል",
          "Search A movie":"ፊልም ድለዩ",
          "Time:":"ግዜ:",
          
          "Date:":"ዕለት:",
          "General": "ሓፈሻዊ", 
          "Forgot password?:":"ፓስዎርድ ረሲዕካ?:",
          "Not a member?:":"ኣባል ኣይኮነን?:",
          "Nearby Theatre":"ኣብ ቀረባ ትያትር",
          "enter location:":"ቦታ ኣእቱ"
         
        }
      };
}
